### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by roozbeh360** [Shaygan/AffiliateBundle#2]
i am getting this

FatalErrorException: Error: Call to undefined method Symfony\Component\HttpKernel\Event\FilterResponseEvent::isMasterRequest() in G:\server\xampp\htdocs\saba_filestore\vendor\shaygan\affiliate-bundle\Shaygan\AffiliateBundle\EventListener\KernelEventListener.php line 30

**Comment by ghasrfakhri** [comment]
Hi,
I think it is a incompatibility bug so I disabled checking master request. due to using session for storing "ref" this change do not have any side effect.
